version: "3"

services:
  cyphernode:
    # Bitcoin Mini Proxy
    env_file:
      - proxy_docker/env.properties
    image: btcproxyimg
#    ports:
#      - "8888:8888"
    volumes:
      # Variable substitutions don't work
      # Match with DB_PATH in proxy_docker/env.properties
      - "~/btcproxydb:/proxy/db"
      - "~/lndata:/proxy/.lightning"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER /proxy/startproxy.sh
    networks:
      - cyphernodenet

  proxycronnode:
    # Async jobs
    env_file:
      - cron_docker/env.properties
    image: proxycronimg
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    networks:
      - cyphernodenet

  pycoinnode:
    # Pycoin
    env_file:
      - pycoin_docker/env.properties
    image: pycoinimg
#    ports:
#      - "7777:7777"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER /pycoin/startpycoin.sh
    networks:
      - cyphernodenet

  clightningnode:
    # c-lightning lightning network node
    image: clnimg
    ports:
      - "9735:9735"
    volumes:
      - "~/lndata:/.lightning"
#    deploy:
#      placement:
#        constraints: [node.hostname==dev]
    command: $USER lightningd
    networks:
      - cyphernodenet

  btcnode:
    # Bitcoin node
    image: btcnode
#    ports:
#      - "18333:18333"
#      - "18332:18332"
#      - "29000:29000"
#      - "8333:8333"
#      - "8332:8332"
    volumes:
      - "~/btcdata:/.bitcoin"
    command: $USER bitcoind
    networks:
      - cyphernodenet

networks:
  cyphernodenet:
    external: true
